apiVersion: v2
name: dep-chart
description: A Helm chart for Kubernetes
type: application
version: 0.2.0
appVersion: 1.16.0

dependencies:
  - name: prometheus
    version: "11.1.*"
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: prometheus.enabled
    tags: 
      - monitoring
  - name: grafana
    version: "5.0.*"
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: grafana.enabled
    tags: 
      - monitoring
  - name: kiam
    version: "5.7.*"
    repository: https://uswitch.github.io/kiam-helm-charts/charts/
    condition: kiam.enabled
    tags: 
      - iam
  - name: cert-manager
    version: "0.15.*"
    repository: https://charts.jetstack.io/
    condition: cert-manager.enabled
    tags: 
      - iam
  - name: elasticsearch
    version: "7.6.*"
    repository: "https://helm.elastic.co"
    condition: elasticsearch.enabled
    tags:
      - elk
  - name: filebeat
    version: "7.6.*"
    repository: "https://helm.elastic.co"
    condition: filebeat.enabled
    tags:
      - elk
  - name: logstash
    version: "7.6.*"
    repository: "https://helm.elastic.co"
    condition: logstash.enabled
    tags:
      - elk
  - name: kibana
    version: "7.6.*"
    repository: "https://helm.elastic.co"
    condition: kibana.enabled
    tags:
      - elk
  - name: traefik
    version: "1.86.*"
    repository: "@stable"
    condition: traefik.enabled
