# This is a basic workflow to help you get started with Actions

name: Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1
      - name: Prep helm chart
        run: |
          mv ./back-rep/Chart.yaml ./back-rep/Chart.old.yaml &&
          cat ./back-rep/Chart.old.yaml | grep -v appVersion > ./back-rep/Chart.yaml &&
          echo -e "\r\nappVersion: v${GITHUB_REF##*/}\r\n" >> ./back-rep/Chart.yaml &&
          cat ./back-rep/Chart.yaml
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@master
        with:
          exec: helm install back-2 ./back-rep/ --set=app.name=APP_NAME --values=./.helm/app/values.yaml --set access_key="${{ secrets.db_access_key }}" --set secret_key="${{ secrets.db_secret_key }}" --set region="us-west-2"
          kubeconfig: '${{ secrets.KKUBECONFIG_vlad }}'



